### ISSUE TITLE
'7z' is not recognized

### ISSUE THREAD

**Issue by steviesteveston** [chevdor/ethereum-chocolatey#6]
I seem to be having a problem with the 7zip that chocolatey installs.  When I try to install alethzero, I get an error that says "[ERROR] -  7z : The term '7z' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spe'

I know that Chocolatey has installed 7zip, I also have 7zip installed on my computer outside of chocolatey.

I have tried completely uninstalling 7zip from my system and then running a new chocolatey install.  

What am I doing wrong?  Running Windows 8.1

**Comment by chevdor** [comment]
Hello Carlos,

I am afraid you are probably not doing anything wrong.
I suspect an issue in the 7z package. I have seen that already without
having the time to dig in the issue.
If you have 7zip installed on your system, then the 7z command should work
(let´s exclude from what I said the mini install that chocolatey does, I am
not sure it takes care of any env variable...). If you did install 7zip and
7z does not work, then the PATH is probably wrong.

If you did install the 7zip chocolatey package, I suggest you check your
PATH and add the folder where the bin is located.
Running the alethzero install will then work just fine.

I guess I could also use the 7z binary shipped with chocolatey. It may be a
better option. I will look into that when I find a little time.

**Comment by marimes** [comment]
Hi chevdor,
I ran into the same problem running Windows 7. I installed 7zip separately before, the command 7z is recognized and PATH includes "C:\Program Files\7-Zip" which contains the executable.

**Comment by chevdor** [comment]
Could you guys tell me which version of chocolatey you have and if you try installing the -latest or -stable version of the package ?

**Comment by chevdor** [comment]
Hi,

I just tried installing -latest. I did get a similar error and the 7zip command (7za) was not found on my system.

I could not uninstall it since some other package depend on it but I could reinstall using:
`cinst -force 7zip.commandline`

Could you please try that and let me know if the issue remains?
If so, please paste the output of your console.

**Comment by marimes** [comment]
I have tried to install -stable using Chocolatey v0.9.9.6.

Marius Messerli, Ph.D.
Founder and Lead Activist
Mindliner AG
Mobile: +41 79 402 5404
Office: +41 52 551 0057
http://www.mindliner.com
Am 29.05.2015 11:00:25 schrieb Chevdor notifications@github.com:
Could you guys tell me which version of chocolatey you have and if you try installing the -latest or -stable version of the package ?

---

**Comment by marimes** [comment]
This is what you get after re-installing 7zip.commandline and then installing AlethZero-Stable.

C:\Users\marius\Desktop\cmder>cinst -force 7zip.commandline
Chocolatey v0.9.9.6
Installing the following packages:
7zip.commandline
By installing you accept licenses for the packages.

7zip.commandline v9.20.0.20130618 (forced)
The package 7zip.commandline wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
1
 Extracting C:\Users\marius\AppData\Local\Temp\chocolatey\7zip.commandline\7zip.commandlineInstall.zip to C:\ProgramData\chocolatey\lib\7zip.commandline\tools...
 C:\ProgramData\chocolatey\lib\7zip.commandline\tools
 ShimGen has successfully created a shim for 7za.exe
 The install of 7zip.commandline was successful.

Chocolatey installed 1/1 package(s). 0 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

C:\Users\marius\Desktop\cmder>cinst -pre AlethZero-Stable
Chocolatey v0.9.9.6
Installing the following packages:
AlethZero-Stable
By installing you accept licenses for the packages.

AlethZero-Stable v0.8.2.3-POC8
The package AlethZero-Stable wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
1
 Bad numeric constant: 7.
 At C:\ProgramData\chocolatey\lib\AlethZero-Stable\tools\chocolateyInstall.ps1:1
 3 char:2
- 7 <<<< z x -aoa -y -o"$env:ProgramFiles\$packageName\" "$destination"
  - CategoryInfo          : ParserError: (7:String) [], ParseException
    The install of alethzero-stable was NOT successful.
  - FullyQualifiedErrorId : BadNumericConstant
    Error while running 'C:\ProgramData\chocolatey\lib\AlethZero-Stable\tools\chocolateyInstall.ps1'.
    See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
- alethzero-stable

C:\Users\marius\Desktop\cmder>

**Comment by chevdor** [comment]
Hi @marimes 

It sounds like you are  running into 2 issues here. 

First, the 'BadNumeric' issue which is probably something I can improve in the package as suggested here (http://stackoverflow.com/questions/4443540/executing-an-exe-in-your-path-which-starts-with-a-numeric-value-in-powershell)

But I thinik you are running into another issue. If you look at the install script of the package (ethereum-chocolatey/alethzero-stable/tools/chocolateyInstall.ps1) you will see that it no longer calls the 7z command as it seems to be the case for you.

So I suspect that you got an old version of the package that is now taken from your cache (-force does not change that).

I suggest you clear your nuget cache and try again. At least I would expect the message then to complain about 7za and not 7z. That would leave just the BadNumeric issue.

**Comment by chevdor** [comment]
@marimes 
I close the 7z issue as it should not occure if you use the latest package.
Let me know however if you still run into the issue.

For the second issue your mentioned, please see #7
